### ISSUE TITLE
"type":"module" breaks playwright-vscode extension (Minimum example from "Playwright:Getting Started" with Typescript)

### ISSUE THREAD

**Issue by iva2k** [microsoft/playwright-vscode#174]
I got an issue with playwright-vscode and TypeScript that looks similar to #120, #168, #169.

 I distilled it down to a minimum repro per [Playwright:Getting Started](https://playwright.dev/docs/intro) using TypeScript and `"type": "module"`, so I believe it has nothing to do with Svelte in #169, React in #168. Removing "type":"module" from package.json seems to fix this.

```bash
npm init playwright@latest playwright-ts
# Getting started with writing end-to-end tests with Playwright:
# Initializing project in 'playwright-ts'
# √ Do you want to use TypeScript or JavaScript? · TypeScript
# √ Where to put your end-to-end tests? · tests
# √ Add a GitHub Actions workflow? (y/N) · false
# Initializing NPM project (npm init -y)…
# Wrote to C:\dev\playwright\playwright-ts\package.json:
# ...

cd playwright-ts
code .
```

This works fine.

Now add `"type": "module"` to "package.json", and relaunch VSCode, the spinner is stuck on "Testing" tab, running tests throws a bunch (open terminal with "Show Output" icon in Testing tab toolbar):

```bash
(node:55672) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

Running 0 test using 0 worker


file:///c:/dev/playwright/playwright-ts/tests/example.spec.ts:1
import { test, expect, Page } from '@playwright/test';
                       ^^^^
SyntaxError: The requested module '@playwright/test' does not provide an export named 'Page'

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at importModuleDynamicallyWrapper (node:internal/vm/module:435:15)
    at Loader._requireOrImport (c:\dev\playwright\playwright-ts\node_modules\@playwright\test\lib\loader.js:275:28)
    at Loader.loadTestFile (c:\dev\playwright\playwright-ts\node_modules\@playwright\test\lib\loader.js:164:7)
    at Runner._runFiles (c:\dev\playwright\playwright-ts\node_modules\@playwright\test\lib\runner.js:289:25)
    at Runner._run (c:\dev\playwright\playwright-ts\node_modules\@playwright\test\lib\runner.js:224:12)
    at TimeoutRunner.run (c:\dev\playwright\playwright-ts\node_modules\playwright-core\lib\utils\timeoutRunner.js:53:14)
    at raceAgainstTimeout (c:\dev\playwright\playwright-ts\node_modules\playwright-core\lib\utils\timeoutRunner.js:113:15)
    at Runner.runAllTests (c:\dev\playwright\playwright-ts\node_modules\@playwright\test\lib\runner.js:182:20)
    at runTests (c:\dev\playwright\playwright-ts\node_modules\@playwright\test\lib\cli.js:162:18)
    at Ai.<anonymous> (c:\dev\playwright\playwright-ts\node_modules\@playwright\test\lib\cli.js:70:7)

=================
 no tests found.
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: EBADF: bad file descriptor, close
Emitted 'error' event on WriteStream instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4083,
  code: 'EBADF',
  syscall: 'close'
}

Node.js v18.1.0
```

VSCode testing is stuck at this point, need to relaunch VSCode. 

Ok, the first is easy, just change (BTW, it is a separate issue, worth fixing):

```js
- import { test, expect, Page } from '@playwright/test';
+ import { test, expect, type Page } from '@playwright/test';
```

Now it always gets a spinner in Testing tab, and trying to run tests from the Testing tab gets this error:

```bash

(node:62444) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

Running 25 tests using 4 workers

node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: EBADF: bad file descriptor, close
Emitted 'error' event on WriteStream instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4083,
  code: 'EBADF',
  syscall: 'close'
}

Node.js v18.1.0
```

Additional info:

* Running tests from VSCode terminal "playwright test" runs ok.
* Debug of tests via extension / Testing tab works fine. It even lists the tests under the stuck spinner.
* Trying the "Playwright:Getting Started" example without TypeScript, and adding "type": "module" breaks VSCode extension more, it won't load at all, and running playwright in terminal won't work due to .js files need to be .cjs.

**Comment by Xtrah** [comment]
Same problem with a stuck spinner, sometimes it doesn't even list the tests under the spinner.

Removing `"type": "module"` fixes it, but that wouldn't be compatible with frameworks such as Svelte.

**Comment by AdelBeit** [comment]
I'm still having this issue. tested with these versions
"@playwright/test": "^1.41.0-alpha-jan-12-2024" (@playwright/test@next as mentioned in the linked PR)
"@playwright/test": "^1.40.1"

when I add type: module, it breaks, when I remove it, it works again.

**Comment by mxschmitt** [comment]
@AdelBeit please file a new issue here: https://github.com/microsoft/playwright/issues

We usually don't monitor closed issues.
