### ISSUE TITLE
The test sidebar doesn't show up

### ISSUE THREAD

**Issue by Tyriar** [microsoft/playwright-vscode#27]
I tried to use the extension for [Luna Paint](https://marketplace.visualstudio.com/items?itemName=Tyriar.luna-paint) but test icon doesn't show up in the activity bar. The extension is closed source but I can check diagnostics if helpful.

Playwright Test output channel:

```
2021-08-23T13:34:31.248Z Executing command: node_modules\@playwright\test\lib\cli\cli.js test --reporter=json --list \. 
```

Looks like this is the cause:

```
❯ node node_modules\@playwright\test\lib\cli\cli.js test --reporter=json --list
Error: Cannot find module '../../../../typings/luna.js'
Require stack:
- D:\GitHub\lunapaint\vscode-luna\luna\src\playwright\platform\format\webp.integration.test.ts
- D:\GitHub\lunapaint\vscode-luna\luna\node_modules\@playwright\test\lib\test\loader.js
- D:\GitHub\lunapaint\vscode-luna\luna\node_modules\@playwright\test\lib\test\runner.js
- D:\GitHub\lunapaint\vscode-luna\luna\node_modules\@playwright\test\lib\test\cli.js
- D:\GitHub\lunapaint\vscode-luna\luna\node_modules\@playwright\test\lib\cli\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\GitHub\lunapaint\vscode-luna\luna\src\playwright\platform\format\webp.integration.test.ts:4:1) 
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._compile (D:\GitHub\lunapaint\vscode-luna\luna\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.newLoader (D:\GitHub\lunapaint\vscode-luna\luna\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Loader._requireOrImport (D:\GitHub\lunapaint\vscode-luna\luna\node_modules\@playwright\test\lib\test\loader.js:211:18)
    at Loader.loadTestFile (D:\GitHub\lunapaint\vscode-luna\luna\node_modules\@playwright\test\lib\test\loader.js:130:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\GitHub\\lunapaint\\vscode-luna\\luna\\src\\playwright\\platform\\format\\webp.integration.test.ts',
    'D:\\GitHub\\lunapaint\\vscode-luna\\luna\\node_modules\\@playwright\\test\\lib\\test\\loader.js',
    'D:\\GitHub\\lunapaint\\vscode-luna\\luna\\node_modules\\@playwright\\test\\lib\\test\\runner.js',
    'D:\\GitHub\\lunapaint\\vscode-luna\\luna\\node_modules\\@playwright\\test\\lib\\test\\cli.js',
    'D:\\GitHub\\lunapaint\\vscode-luna\\luna\\node_modules\\@playwright\\test\\lib\\cli\\cli.js'
  ]
}
```

`../../../../typings/luna.d.ts` does exist at that location so not sure why it's failing. Removing `.js` doesn't fix the issue.

**Comment by mxschmitt** [comment]
Hey Tyriar, is `platform\format\webp.integration.test.ts` a Playwright Test test? (so no Jest, Mocha, etc)?

It seems like you already executed `node node_modules\@playwright\test\lib\cli\cli.js test --reporter=json --list` manually and got so the stack trace?

**Comment by Tyriar** [comment]
Yes to both

**Comment by JoelEinbinder** [comment]
I suspect this has to do with us transforming your code with babel instead of typescript.

Can you show the source of `webp.integration.test.ts` or at least the import lines? Maybe you need to change an import line to use [`import type`](https://devblogs.microsoft.com/typescript/announcing-typescript-3-8-beta/#type-only-imports-exports).

**Comment by Tyriar** [comment]
`import type` works around the module not found issue but it doesn't compile as I have enums with values defined in the .d.ts.

Also then it fails on:

```
import { ... } from '../../testUtil.js';
```

Removing .js fixes this but it's pretty annoying making so many changes, the .js usage I have in the project was needed to work around some other weird packaging issue I was experiencing. If you don't use tsc aren't more issues like these bound to happen?

Is there a way for me to set the tsc out directory with source maps to workaround this?

**Comment by mxschmitt** [comment]
Since we are using babel-typescript under the hood, the TypeScript support is limited and different compared to use TypeScript directly via the CLI. We recently added a docs page how to use a custom setup: https://github.com/microsoft/playwright/blob/c8f3c65d22196098ea04777f32723c5963d24c11/docs/src/test-typescript-js.md this should help in your scenario.

The docs page will soon appear in the docs.

**Comment by Tyriar** [comment]
@mxschmitt not sure what to do with that page wrt getting the extension working, I already do something similar and the tests run just fine via the cli already:

```
"test-playwright": "npx playwright test -c ./out/playwright/playwright.config.js --workers 4"
```

**Comment by JoelEinbinder** [comment]
We currently match tests against the name on disk, but we should take into account source maps.

**Comment by pavelfeldman** [comment]
@Tyriar: I'm rewriting the extension, could you help me reproducing this issue? What should be my steps? I can only see images in https://github.com/lunapaint/vscode-luna-paint.

**Comment by Tyriar** [comment]
@pavelfeldman the extension is closed source unfortunately. Here's the playwright.config.ts and related tsconfigs that the error was complaining about if that's helpful:

```ts
import { PlaywrightTestConfig } from '@playwright/test';

const config: PlaywrightTestConfig = {
  testDir: '.',
  timeout: 15000,
  workers: 2,
  retries: 1,
  projects: [
    {
      name: 'Chrome Stable',
      use: {
        browserName: 'chromium',
        channel: 'chrome',
      },
    },
  ],
  webServer: {
    command: 'yarn start-server',
    port: 3000,
    reuseExistingServer: true
  },
  forbidOnly: !!process.env.CI,
  reportSlowTests: null
};
export default config;
```

And the tsconfig.json:

```json
{
  "extends": "../tsconfig.node.json",
  "compilerOptions": {
    "outDir": "../../out/test",
    "rootDir": ".",
    "types": [
      "../../node_modules/@types/mocha",
      "../../node_modules/@types/node"
    ]
  },
  "include": [
    "./**/*",
    "../../../typings/luna.d.ts"
  ],
  "references": [
    // ...some entries
  ]
}
```

 tsconfig.node.json:

```json
{
  "extends": "./tsconfig.base.json",
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2016",
    "lib": [],
    "types": [
      "node"
    ]
  }
}
```

tsconfig.base.json:

```json
{
  "compilerOptions": {
    "types": [],
    "composite": true,
    "strict": true,
    "sourceMap": true,
    "removeComments": true,
    "pretty": true,
    "incremental": true,
    "noImplicitOverride": true
  }
}
```

**Comment by pavelfeldman** [comment]
Do I understand it right that Playwright works fine, you can see all the reports ok, but extension does not work?

**Comment by Tyriar** [comment]
Yes I can run my tests fine via command line, just the extension doesn't work
